### ISSUE TITLE
Xcode 26 on Tahoe breaks Ably networking. Works in Xcode 16.3

### ISSUE THREAD

**Issue by nicholasdiiorio** [ably/ably-dotnet#1314]
I updated my mac mini (2023) to Tahoe. I then updated Xcode from 16.3 to 26.0.1 and builded my application without doing any changes. Ably realtime could not make a connection. Ably error : [reason: [ErrorInfo Reason: Object reference not set to an instance of an object
Code: 80000; StatusCode: 503 (ServiceUnavailable)]]

IOS console simultaneously logs : nw_connection_copy_protocol_metadata_internal on unconnected nw_connection

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-5636) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
Hi @nicholasdiiorio, thanks for raising this issue.
Could you please provide a few more details?

What type of project are you using — Xamarin or .NET MAUI?
Which version of .NET are you running (e.g., .NET 6, .NET 7, etc.)?
Could you share the relevant logs? You can enable logging by using...

```
class CustomLogHandler : ILoggerSink
{
    public void LogEvent(LogLevel level, string message)
    {
        Console.WriteLine($"Handler LogLevel : {level}, Data :{message}");
    }
}
```
Update clientOptions for LogLevel and LogHandler.

```
clientOpts.LogLevel = LogLevel.Debug;
clientOpts.LogHandler = new CustomLogHandler();
```

**Comment by nicholasdiiorio** [comment]
Hi sac007, of course.

1. We were using ably.io.1.2.14.unitypackage but updated to 1.2.16 and saw no change. We’re currently on 1.2.16.
2. The project uses the IL2CPP scripting backend for iOS through Unity 2022.3.68f1, so it doesn’t run on a conventional .NET runtime.
3. Unity 2022.3 targets a custom .NET Standard 2.1 compatibility profile (no managed runtime, everything is AOT-compiled to native code).
4. Sure — here are the best logs I could capture of the error (see below).

When archiving or building with any Xcode version newer than 16.3, calling _ablyRealtime.Connect();_ fails at runtime (no connection established).

• If I run from Xcode in Debug mode, it does connect successfully — but of course I can’t ship a Debug build to TestFlight.
• In Xcode 16.3, both Release and Debug builds work perfectly on the same device and same codebase.


Logs :

Built from '2022.3/staging' branch, Version '2022.3.68f1 (5dfc353c715b)', Build type 'Development', Scripting Backend 'il2cpp'
 
 [...]

 nw_endpoint_flow_failed_with_error [C4.1.1 2607:f8b0:4020:802::200e.443 in_progress channel-flow (satisfied (Path is satisfied), viable, interface: en0[802.11], ipv4, ipv6, dns, uses wifi)] already failing, returning
 nw_endpoint_flow_failed_with_error [C4.1.2 142.250.69.78:443 in_progress channel-flow (satisfied (Path is satisfied), viable, interface: en0[802.11], ipv4, ipv6, dns, uses wifi)] already failing, returning
 nw_connection_copy_protocol_metadata_internal_block_invoke [C4] Client called nw_connection_copy_protocol_metadata_internal on unconnected nw_connection
 nw_connection_copy_protocol_metadata_internal_block_invoke [C4] Client called nw_connection_copy_protocol_metadata_internal on unconnected nw_connection
 nw_connection_copy_protocol_metadata_internal_block_invoke [C4] Client called nw_connection_copy_protocol_metadata_internal on unconnected nw_connection
 nw_connection_copy_protocol_metadata_internal_block_invoke [C4] Client called nw_connection_copy_protocol_metadata_internal on unconnected nw_connection
 nw_connection_copy_connected_local_endpoint_block_invoke [C4] Client called nw_connection_copy_connected_local_endpoint on unconnected nw_connection
 nw_connection_copy_connected_path_block_invoke [C4] Client called nw_connection_copy_connected_path on unconnected nw_connection
 nw_connection_copy_connected_remote_endpoint_block_invoke [C4] Client called nw_connection_copy_connected_remote_endpoint on unconnected nw_connection
 nw_connection_copy_protocol_metadata_internal_block_invoke [C4] Client called nw_connection_copy_protocol_metadata_internal on unconnected nw_connection
 nw_connection_copy_protocol_metadata_internal_block_invoke [C4] Client called nw_connection_copy_protocol_metadata_internal on unconnected nw_connection
 nw_connection_copy_metadata_block_invoke [C4] Client called nw_connection_copy_metadata on unconnected nw_connection
 nw_endpoint_flow_failed_with_error [C5.1.1 2607:f8b0:4020:802::200e.443 in_progress channel-flow (satisfied (Path is satisfied), viable, interface: en0[802.11], ipv4, ipv6, dns, uses wifi)] already failing, returning
 nw_endpoint_flow_failed_with_error [C5.1.2 142.250.69.110:443 in_progress channel-flow (satisfied (Path is satisfied), viable, interface: en0[802.11], ipv4, ipv6, dns, uses wifi)] already failing, returning
 nw_connection_copy_protocol_metadata_internal_block_invoke [C5] Client called nw_connection_copy_protocol_metadata_internal on unconnected nw_connection
 nw_connection_copy_protocol_metadata_internal_block_invoke [C5] Client called nw_connection_copy_protocol_metadata_internal on unconnected nw_connection
 nw_connection_copy_protocol_metadata_internal_block_invoke [C5] Client called nw_connection_copy_protocol_metadata_internal on unconnected nw_connection
 nw_connection_copy_protocol_metadata_internal_block_invoke [C5] Client called nw_connection_copy_protocol_metadata_internal on unconnected nw_connection
 nw_connection_copy_connected_local_endpoint_block_invoke [C5] Client called nw_connection_copy_connected_local_endpoint on unconnected nw_connection
 nw_connection_copy_connected_path_block_invoke [C5] Client called nw_connection_copy_connected_path on unconnected nw_connection
 nw_connection_copy_connected_remote_endpoint_block_invoke [C5] Client called nw_connection_copy_connected_remote_endpoint on unconnected nw_connection
 nw_connection_copy_protocol_metadata_internal_block_invoke [C5] Client called nw_connection_copy_protocol_metadata_internal on unconnected nw_connection
 nw_connection_copy_protocol_metadata_internal_block_invoke [C5] Client called nw_connection_copy_protocol_metadata_internal on unconnected nw_connection
 nw_flow_add_write_request [C5 khm2.googleapis.com:443 failed parent-flow (satisfied (Path is satisfied), interface: en0[802.11], ipv4, ipv6, dns, uses wifi)] cannot accept write requests
 nw_write_request_report [C5] Send failed with error "Socket is not connected"
 nw_connection_copy_metadata_block_invoke [C5] Client called nw_connection_copy_metadata on unconnected nw_connection
 <color=#FF2655>POST_Request_Trigger TriggerType.Authenticated response received.</color>
 UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
 UnityEngine.Logger:Log(LogType, Object)
 UnityEngine.Debug:Log(Object)
 CustomDebug:Log(String, Nullable1) (at /Users/splendide/Projects/SuperSublime/repo_ToujoursDimanche/RandoVR/Assets/_RandoVR/Scripts/Tools/CustomDebug.cs:14)
 CustomDebug:Log(String, String) (at /Users/splendide/Projects/SuperSublime/repo_ToujoursDimanche/RandoVR/Assets/_RandoVR/Scripts/Tools/CustomDebug.cs:27)
 <>c:<OnGetShareCodesCallback>b__326_0(RequestCallbackData2) (at /Users/splendide/Projects/SuperSublime/repo_ToujoursDimanche/RandoVR/Assets/_RandoVR/Scripts/Managers/GameDataManager.cs:1196)
 <RequestAsync>d__632:MoveNext() (at /Users/splendide/Projects/SuperSublime/repo_ToujoursDimanche/RandoVR/Assets/_RandoVR/Scripts/Tools/WebRequestManager.cs:1342)
 System.Runtime.CompilerServices.MoveNextRunner:InvokeMoveNext(Object)
 System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
 System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
 System.Runtime.CompilerServices.MoveNextRunner:Run()
 System.Runtime.CompilerServices.YieldAwaiter:RunAction(Object)
 UnityEngine.WorkRequest:Invoke() (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
 UnityEngine.UnitySynchronizationContext:Exec() (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
 UnityEngine.UnitySynchronizationContext:ExecuteTasks() (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
 
 OnAblyConnectionChange : Connecting, Has errored? False, reason: 
 UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
 UnityEngine.Logger:Log(LogType, Object)
 UnityEngine.Debug:Log(Object)
 NetworkManager:OnAblyConnectionChange(Object, ConnectionStateChange) (at /Users/splendide/Projects/SuperSublime/repo_ToujoursDimanche/RandoVR/Assets/_RandoVR/Scripts/Managers/NetworkManager.cs:259)
 IO.Ably.Realtime.<>c__DisplayClass68_0:<NotifyUpdate>b__0()
 IO.Ably.<>c__DisplayClass51_0:<NotifyExternalClients>b__0(Object)
 UnityEngine.WorkRequest:Invoke() (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
 UnityEngine.UnitySynchronizationContext:Exec() (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
 UnityEngine.UnitySynchronizationContext:ExecuteTasks() (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
 
 OnAblyConnectionChange : Disconnected, Has errored? True, reason: [ErrorInfo Reason: Object reference not set to an instance of an object. (See https://help.ably.io/error/80000); Code: 80000; StatusCode: 503 (ServiceUnavailable); Href: https://help.ably.io/error/80000]
 UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
 UnityEngine.Logger:Log(LogType, Object)
 UnityEngine.Debug:Log(Object)
 NetworkManager:OnAblyConnectionChange(Object, ConnectionStateChange) (at /Users/splendide/Projects/SuperSublime/repo_ToujoursDimanche/RandoVR/Assets/_RandoVR/Scripts/Managers/NetworkManager.cs:259)
 IO.Ably.Realtime.<>c__DisplayClass68_0:<NotifyUpdate>b__0()
 IO.Ably.<>c__DisplayClass51_0:<NotifyExternalClients>b__0(Object)
 UnityEngine.WorkRequest:Invoke() (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
 UnityEngine.UnitySynchronizationContext:Exec() (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
 UnityEngine.UnitySynchronizationContext:ExecuteTasks() (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
 
 [...]

**Comment by sacOO7** [comment]
If the above doesn't work, then from our side, we can try following ( but success is not guaranteed )
- Adding null checks before accessing connection metadata
- Delaying connection metadata access until connection state is confirmed  
- Using alternative APIs that are compatible with the new networking stack

or 

### **Report to Unity**
This appears to be a broader IL2CPP + Xcode 16.4+ compatibility issue. Consider filing a bug report with Unity, referencing similar issues like their bug tracker issue 1358995 mentioned in the Ably GitHub issues.

**Comment by sacOO7** [comment]
@nicholasdiiorio as per documentation
> Xcode 26 and iOS 26 were released in September 2025, and this major version bump introduced significant changes and deprecations, including a move to newer .NET toolchains and updated SDK policies

It appears there's a networking-related issue introduced on Apple's end. If that's the case, Unity would need to release a patch addressing it as part of the IL2CPP build. Ultimately, the fix should come from either Apple or Unity. Alternatively, if Apple responds to the above query with guidance on fixing the client-side configuration, we can update the ably-dotnet/ably-unity library accordingly.

**Comment by sacOO7** [comment]
> I’ve already sent a bug report to Apple last Friday describing the regression between Xcode 16.3 and 26.x. I’m currently waiting for their response.

- You might also consider raising this issue on Apple’s GitHub repository, if it's publicly accessible.
- Here's the link to the Xcode 26 release notes: https://developer.apple.com/documentation/xcode-release-notes/xcode-26-release-notes"
- By the way, we’re aligned that ably-unity works correctly in the Xcode 26 `debug build`, right?

**Comment by Whyser** [comment]
Sorry for the poke but @nicholasdiiorio did you ever get a response/solution? 
I've got a similar issue (but not with the ably SDK). For me it works fine in xCode 16 but when using xCode 26.3 some classes seems to get stripped and cause null ref.
Disabling Dead Code Stripping did not work for me either.

**Comment by nicholasdiiorio** [comment]
Hi @Whyser ,

Unfortunately no, we never found a proper fix. I tried multiple updates from Ably and tested across different Xcode versions, but the issue was never resolved.

Apple did respond at one point asking for more details, but after that they stopped replying. The Ably team was more helpful, though it didn’t feel like the issue was fully investigated or resolved on their side either.

With the April 2026 deadline approaching fast (when Apple will restrict publishing from older Xcode versions that don’t have this bug), we’ve decided to move away from Ably.

We’re currently finishing a transition to using raw WebSockets via Google Cloud Run and Unity’s native implementation (System.Net.WebSockets), and with the recent Google native WebSocket implementation it’s been working really well. Good luck if you try.

It’s not something we wanted to do initially, but reducing dependencies is probably a good long-term move anyway. 👍

**Comment by Whyser** [comment]
Thanks for the reply! 
I've been scouring the internet all day today and actually found a solution (albeit not a good one). My issue was solved by enabling Incremental GC in Unity (yes very odd solution).
Would be interesting if this would've solved your issue as well, but I'm guessing you don't really have any reason to try it out any more.

**Comment by nicholasdiiorio** [comment]
Ah man, if we knew!
I tried almost everything but yeah, we it's too late for us. It was nice of you to update us with a solution, if it can help anyone else.

**Comment by nicholasdiiorio** [comment]
I went back and built an older branch of our Unity app (from when we were still experiencing the issue with Ably), and simply enabling Incremental GC made it work again.

So I can confirm your unexpected solution worked for us too for Unity 2022.71f1 (LTS).

This definitely gives our team some closure on the whole situation, thank you again.
