### ISSUE TITLE
Xamarin build support

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#32]
Builds are currently failing because of a missing Xamarin target, see https://travis-ci.org/ably/ably-dotnet/builds/99849811

We need to add Xamarin support in Travis.  I have found a few examples online where it appears Xamarin is supported:

* http://stackoverflow.com/questions/16751772/how-do-i-use-travis-ci-with-c-sharp-or-f
* https://github.com/travis-ci/travis-ci/issues/649#issuecomment-20093291
* http://code.openhub.net/file?fid=vJtKJ6n2yxThIbvd9zaNSnYaCw4&cid=FJ9m9rJSR3k&s=&fp=507212&mp&projSelected=true#L0

**Comment by mattheworiordan** [comment]
@Const-me is this resolved with #35?

**Comment by Const-me** [comment]
No, not resolved.

And no, xamarin isn’t supported.
Looks like xamarin uses some .NET DLLs from xamarin’s OSX package.
That’s why you see words “xamarin” and “travis” together in the google output.

**Comment by marto83** [comment]
Xamarin support exists from version 0.8.3. 
Support for portable libraries will come in future releases.
